### PR TITLE
Python3 compatibility

### LINKED ISSUE #15: Not compatible with Python 3

### PR DESCRIPTION
**Pull request by chrsmutti**
I ran the [2to3](https://docs.python.org/2/library/2to3.html) tool and added some minor changes to enable python3 compatibility, and then also added the `from __future__ import print_function` statement to maintain python2 compat.

Tested in Arch Linux, Python 3.7.3 and Python 2.7.16.

Closes #15.

### CODE REVIEW

**Comment by fxcoudert** [comment]
These changes all look fine. With Python 2 EOL in 2 months (https://pythonclock.org), we will need a new release of `git-plus` before the end of the year if we are to continue shipping it in Homebrew.

**Comment by iMichka** [comment]
Hi. Could you make yet another release? I think we will need these changes too: https://github.com/tkrajina/git-plus/commit/f7ca1fbb97f24d2af24a08f305c9a450336fca0d

Thanks!

**Comment by tkrajina** [comment]
@iMichka submitted now.

**Comment by iMichka** [comment]
Thanks! I opened a PR to update it on homebrew: https://github.com/Homebrew/homebrew-core/pull/47830

**Pull request merged**
